exclude = ["docs"]

# Enable flake8-bugbear (`B`) rules.
lint.select = [
    "B", "E", "F", "PL", "S", "W", "N", "G", "C4", "EM",
    "ISC", "ICN", "PIE", "T20", "PYI", "PT", "RET", "INT", "RUF",
    # "D",
]

line-length = 120
lint.ignore = [
    "B905",  # `zip()` without an explicit `strict=` parameter
    "D401",  # Disable "non-imparative-mood for docstrings
    "D203",  # One blank line before class
    "D212",  # Disable multi-line-summary-first-line
    "D106",  # Disable missing docstrings for pulic nested classes (Meta class)
    "PT009",  # Use a regular `assert` instead of unittest-style `{assertion}`
    "S308",  # Use of `mark_safe` may expose cross-site scripting vulnerabilities
    "PLR2004",  # magic-value-comparison
    "N813", # Camelcase `BeautifulSoup` imported as lowercase `bs`
    "PLR0912", # Too many branches
    "PLR0915", # Too many statements
    "RUF012", # Mutable class attributes should be annotated with `typing.ClassVar`
]

# Ignore `E501` (line length) in all `__init__.py`  and migration files
[lint.per-file-ignores]
"__init__.py" = ["E501"]
"**/migrations/*.py" = ["E501"]
